name: Sync All
description: Sync secrets & files between groupped GitHub repos
branding:
branding:
  color: blue
  icon: copy
inputs:
  config_file:
    description: .json file with sync config
    required: true
  github_token:
    description: Token to use to get repos and write secrets
    required: true
  # add_generated_note:
  #   description: Whether add a GENERATED comment on the top of supported files (.js, .yml) or not
runs:
  using: 'node14'
  main: 'dist/index.js'
