name: Sync All
description: Sync secrets & files between groupped GitHub repos
branding:
  color: blue
  icon: copy
inputs:
  test:
    description: true
    required: false
    default: "$GITHUB_ACTOR"
  # add_generated_note:
  #   description: Whether add a GENERATED comment on the top of supported files (.js, .yml) or not
runs:
  using: "node12"
  main: "dist/index.js"
