name: Test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     path: ./test
      - run: echo ${{ github.base_ref }}
      # - uses: zardoy/sync-all@main
