name: Test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: |
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - run: pnpx i -g tsm
      - run: tsm test.ts
      # - name: Dump Github context
      #   run: echo "$GITHUB_CONTEXT"
      #   env:
      #     GITHUB_CONTEXT: ${{ toJSON(github) }}
